spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_aggregator_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    mongodb:
      uri: mongodb://localhost/news_aggregator


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.lunazkoe.naa: trace